--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/DiscordWebhooksX
branches:
- PM4
projects:
  DiscordWebhooksX:
    model: virion
    type: library
    lint:
      phpstan: true
...
